const optionsRubros = [
	{ value: "ACEITES", label: "ACEITES" },
	{ value: "AEROS  DESO - DESINFECT", label: "AEROS  DESO - DESINFECT" },
	{ value: "Alcohol", label: "Alcohol" },
	{ value: "ALIMENTACIÓN SALUDABLE", label: "ALIMENTACIÓN SALUDABLE" },
	{ value: "ALIMENTO BALANCEADO", label: "ALIMENTO BALANCEADO" },
	{ value: "BATERÍAS", label: "BATERÍAS" },
	{ value: "BEBIDA A BASE DE HIERBAS", label: "BEBIDA A BASE DE HIERBAS" },
	{ value: "BEBIDA APERITIVO", label: "BEBIDA APERITIVO" },
	{ value: "BEBIDA READY TO DRINK", label: "BEBIDA READY TO DRINK" },
	{ value: "BEBIDAS CERVEZAS", label: "BEBIDAS CERVEZAS" },
	{ value: "Bonificaciones", label: "Bonificaciones" },
	{ value: "CIGARRILLOS", label: "CIGARRILLOS" },
	{ value: "COLONIAS", label: "COLONIAS" },
	{ value: "COSMETICOS", label: "COSMETICOS" },
	{ value: "CUIDADO DE LA SALUD", label: "CUIDADO DE LA SALUD" },
	{ value: "CUIDADO DEL BEBE", label: "CUIDADO DEL BEBE" },
	{ value: "CUIDADO DEL CABELLO", label: "CUIDADO DEL CABELLO" },
	{ value: "CUIDADO DENTAL", label: "CUIDADO DENTAL" },
	{ value: "CUIDADO FEMENINO", label: "CUIDADO FEMENINO" },
	{ value: "DESODORANTE PARA PISOS", label: "DESODORANTE PARA PISOS" },
	{ value: "Espumante", label: "Espumante" },
	{ value: "DESODORANTES", label: "DESODORANTES" },
	{ value: "DETERGENTES", label: "DETERGENTES" },
	{ value: "Electronica", label: "Electronica" },
	{ value: "Encendedores", label: "Encendedores" },
	{ value: "ENCURTIDO", label: "ENCURTIDO" },
	{ value: "Energizantes", label: "Energizantes" },
	{ value: "ESPECIAS", label: "ESPECIAS" },
	{ value: "ESPUMAS Y GELES DE AFEITAR", label: "ESPUMAS Y GELES DE AFEITAR" },
	{ value: "GOLOSINAS", label: "GOLOSINAS" },
	{ value: "INSECTICIDAS Y FLUIDOS", label: "INSECTICIDAS Y FLUIDOS" },
	{ value: "JABON DE TOCADOR", label: "JABON DE TOCADOR" },
	{ value: "JABON LIQUIDO", label: "JABON LIQUIDO" },
	{ value: "JABONES PARA LA ROPA", label: "JABONES PARA LA ROPA" },
	{ value: "Lamparas", label: "Lamparas" },
	{ value: "LAVANDINAS", label: "LAVANDINAS" },
	{ value: "LIMPIEZA E HIGIENE", label: "LIMPIEZA E HIGIENE" },
	{ value: "LINTERNAS", label: "LINTERNAS" },
	{ value: "LUSTRADORES", label: "LUSTRADORES" },
	{
		value: "MÁQUINAS Y SISTEMAS DE AFEITAR",
		label: "MÁQUINAS Y SISTEMAS DE AFEITAR",
	},
	{ value: "MATERIAL POP", label: "MATERIAL POP" },
	{ value: "OFERTAS Y PROMOCIONES", label: "OFERTAS Y PROMOCIONES" },
	{ value: "Pañuelos", label: "Pañuelos" },
	{ value: "Preservativos", label: "Preservativos" },
	{ value: "PROTECTORES SOLARES", label: "PROTECTORES SOLARES" },
	{ value: "SALES", label: "SALES" },
	{ value: "SPIRIT", label: "SPIRIT" },
	{
		value: "SUAVIZANTES Y CREMAS PARA ROPA",
		label: "SUAVIZANTES Y CREMAS PARA ROPA",
	},
	{ value: "TALCO", label: "TALCO" },
	{ value: "TINTURAS PARA CABELLO", label: "TINTURAS PARA CABELLO" },
	{ value: "VELAS", label: "VELAS" },
	{ value: "VINOS 750", label: "VINOS 750" },
	{ value: "VINOS SEGMENTO BAJO", label: "VINOS SEGMENTO BAJO" },
];

const optionsClientes = [
	"Cliente A",
	"Cliente B",
	"Cliente C",
	"Cliente D",
	"Cliente E",
];
export { optionsRubros, optionsClientes };
